spring:
  config:
    active:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/demo_spring_jpa_data'
    username: root
    password: '@Ttg123456'
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: true
      hibernate:
        ddl-auto: none


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: api-service
    server: http://localhost:${server.port}
    title: API Document
    version: 1.0.0
